# Practica Pandas

consigna:
* Cargar un archivo .csv en un dataframe
* Cargar una planilla excel en un dataframe
* Rellenar nulos de una columna (fillna)
* Filtrar filas haciendo que alguna columna cumpla una condición
* Realizar alguna agregación (group by)

In [6]:
import pandas as pd #importar la libreria pandas

df = pd.read_csv("figuras_geometricas.csv") #df es la variable donde guardo el dataframe
df.head() #para ver las primeras filas y chequear que se cargo bien

   id      figura    color  tamaño_cm
0   1     círculo   blanco         45
1   2    cuadrado  violeta         46
2   3  rectángulo    negro         24
3   4   triángulo  violeta         97
4   5    hexágono     azul         70

In [7]:
df.info()

df.isnull().sum() #aca chequeo que hay 3 figuras nulas y 6 colores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         60 non-null     int64
 1   figura     57 non-null     object
 2   color      54 non-null     object
 3   tamaño_cm  60 non-null     int64
dtypes: int64(2), object(2)
memory usage: 2.0+ KB

id           0
figura       3
color        6
tamaño_cm    0
dtype: int64

In [8]:
df['figura'] = df['figura'].fillna("Sin figura") #haciendo asi, llena los valores en el dataframe original
df.isnull().sum() #se ve que ya no hay mas nulos

id           0
figura       0
color        6
tamaño_cm    0
dtype: int64

In [9]:
df['color'] = df['color'].fillna("Sin color")
df.isnull().sum()

id           0
figura       0
color        0
tamaño_cm    0
dtype: int64

In [10]:
df[(df['tamaño_cm'] > 90)] #figuras que el tamaño sea mayor a 90 cm

    id      figura      color  tamaño_cm
3    4   triángulo    violeta         97
8    9    hexágono  Sin color         99
31  32   triángulo     blanco        100
32  33  rectángulo      negro         97
37  38    hexágono       azul         99
55  56     círculo       rojo         92

In [11]:
df.groupby("color")["tamaño_cm"].mean() #promedio de tamaño de figuras por color

color
Sin color    71.833333
amarillo     65.750000
azul         52.571429
blanco       62.500000
negro        44.285714
rojo         54.875000
verde        57.666667
violeta      39.222222
Name: tamaño_cm, dtype: float64